shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include('accounts.urls')),
    path("store/", include(('store.urls', 'store'), namespace='store')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "store.views.handle404"

shop/store/urls.py
from .views import *
from django.urls import path


urlpatterns = [
    path("" , home , name="home"),
    path("contact/" , contact , name="contact"),
    path("create/", Productcreate.as_view(), name="create"),
    path("listproduct/", ListProduct, name="listproduct"),
    path("detail/<int:pk>", ProductDetailView.as_view(), name="detail"),
    path("search/" , search , name="search"),
    path("detail/<int:pk>/add-to-cart" , add_to_cart , name="add-to-cart"),
    path("cart/" , cart , name="cart"),
    path("cart/delete" , cart_delete , name="cart-delete"),
    path("from-pai/" , form_pai , name="form-pai"),
    path("alivre/", OrderListView.as_view(), name="alivre"),
    path("<int:pk>/editorder" , OrderUpdateView.as_view() , name="editorder"),
    path('checkout/', checkout, name='checkout'),
    path('payment/execute/', execute_payment, name='execute_payment'),
    path("paiement" , paiement , name="paiement"),
    path("paiement/recu/<int:pk>" , recu , name="recu"),
    path("paiement/erecu/" , essairecu , name="erecu"),
    
]

shop/store/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from shop.settings import AUTH_USER_MODEL

# Create your models here.

# ----------------------Categorie de produit---------------------------------#
class Categories(models.Model):
    name = models.CharField(max_length=128, )
    descriptions = models.TextField(blank=True)
    
    class Meta:
        verbose_name = "Categorie"

    def __str__(self) -> str:
        return self.name

# ---------------------------Produit (Product)---------------------------------#
class Product(models.Model):
    name = models.CharField(max_length=128, verbose_name="nom du produit")
    # slug = models.SlugField(max_length=128, blank=True)
    price = models.FloatField(verbose_name="prix du produit")
    stock = models.IntegerField(verbose_name="Quantité stoker")
    thumbnail = models.ImageField(upload_to="products", blank=True, null= True)
    description = models.TextField(blank=True, verbose_name="Description du produit")
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Produit"
   

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"pk":self.pk})
    
    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.name)
    #     super().save(*args, **kwargs)

# -----------------------Addresse de livraison-----------------------------------#
class ShippingAddress(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    pays = models.CharField(max_length=32)
    ville = models.CharField(max_length=32)
    zip_code = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.pays} {self.ville} {self.zip_code}"
    

# ---------------------------Panier (cart)------------------------------------------#
class Cart(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

# ---------------------------Article (Order)------------------------------------#
class Order(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="OrderProduct") 
    shippingaddress = models.OneToOneField(ShippingAddress,null=True, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, verbose_name="client", on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=1) 
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    montant = models.FloatField(default=0)
    delivred = models.CharField(max_length=50, choices=([
        ("En_attent","En attente"),
        ("En_cours", "En cours de traitement"),
        ("Annule", "Annulé"),
        ("Livrre", "Livrée")
    ]), default="En_attente", verbose_name="etat")
 
    def __str__(self):
        return f"{self.user} {self.quantity}"
    
    class Meta:
        verbose_name = "Commande"
        ordering = ["-quantity"]

class OrderProduct(models.Model):
    product = models.ForeignKey(Product, verbose_name="Produits", on_delete=models.CASCADE)
    order = models.ForeignKey(Order, verbose_name="commande", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def tatol_amount(self):
        return self.quantity * self.product.price 
        
# -------------------------------Paiement------------------------------------------#
class Paiement(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    mount = models.FloatField(default=0)

    def __str__(self) -> str:
        return f"{self.user.username} {self.mount}" 
    def save(self, *args, **kwargs):
        cart = self.cart
        for order in cart.order_set.all():
            order.ordered = True
            order.ordered_date = timezone.now()
            order.save()
        self.cart.order_set.clear()
        self.cart.order_set.all().delete()


        super().save(*args, **kwargs)

shop/store/forms.py
from django import forms
from .models import Product, Order

class formProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "stock", "thumbnail", "categories", "description"]

    def __init__(self, *args, **kwargs):
        super(formProduct, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'placeholder': self.fields[field].label})
            self.fields[field].label = ''
            
class formOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["user", "delivred"]

    def __init__(self, *args, **kwargs):
        super(formOrder, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
                

shop/store/views.py
from django.http import HttpResponseForbidden, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from store.forms import formProduct, formOrder
from .models import *
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from shop import settings
from weasyprint import CSS, HTML
from django.template.loader import render_to_string

import paypalrestsdk
from django.conf import settings

paypalrestsdk.configure({
    "mode": settings.PAYPAL_MODE,  
    "client_id": settings.PAYPAL_CLIENT_ID,
    "client_secret": settings.PAYPAL_CLIENT_SECRET
})

# Create your views here.
# --------------------------------------------------LA PAGE D'ACCUEIL---------------------------------------------------------------------#
def home(request):
    product = Product.objects.all()[:5]
    return render(request, "store/index.html", context={"product":product})

# ---------------------------------------------PAGE D'ERREUR PERSONNALISER----------------------------------------------------------------#
def handle404(request, exception):
    return render(request, 'store/pages-error-404.html', status=404)

# ------------------------------------------------------------CONTACT---------------------------------------------------------------------#
def contact(request):
    if request.method == 'POST':
        name = request.POST.get('nom')
        email = request.POST.get('email')
        sujet = request.POST.get('sujet')
        message = request.POST.get('message')

        send_mail(
                subject = f"{name} vous a contacter pour le sujet : {sujet}",
                message = message,
                from_email = email,
                recipient_list = [settings.EMAIL_HOST_USER],
                fail_silently=False,
        )
    return render(request, 'store/contact.html')


# -------------------------------------------------AJOUTER UN PRODUIT---------------------------------------------------------------------#
class Productcreate(UserPassesTestMixin,CreateView):
    model = Product
    form_class = formProduct
    def test_func(self) -> bool | None:
        return self.request.user.is_superuser
     
    def handle_no_permission(self): 
        return HttpResponseForbidden("vous n'êtes pas autorisez à naviguer ici")
    success_url = reverse_lazy("store:home")

#-------------------------------------------LISTE DES PRODUITS----------------------------------------------------------------------------#
def  ListProduct(request):
    products = Product.objects.all()
    paginator = Paginator(products, 5)
    page = request.GET.get('page')
    try: 
        prods = paginator.page(page)
    except PageNotAnInteger:
        prods = paginator.page(1)
    except EmptyPage :
        prods = paginator.page(paginator.num_pages)
    return render(request, 'store/product_list.html', {"products": prods})


# ------------------------------------------------LES DETAILS D'UN PRODUIT----------------------------------------------------------------#
class ProductDetailView(DetailView):
    model = Product
    template_name = "store/detail.html"

    
# -----------------------------------------------RECHERCHER UN PRODUIT--------------------------------------------------------------------#
def search(request):
    product = None
    if query := request.GET.get('query'):
        product = Product.objects.filter(name__icontains = query)
        return render(request, 'store/search.html', {'product':product, 'query':query})
    return render(request, 'store/index.html')


# --------------------------------------------AJOUT DE PRODUIT DANS LE PANIER-------------------------------------------------------------#
def add_to_cart(request, pk):
    user = request.user
    product = get_object_or_404(Product, pk=pk)
    cart, _ = Cart.objects.get_or_create(user=user)
    order, _ = Order.objects.get_or_create(user=user, ordered=False)

    order.cart = cart
    # Vérifie si le produit est déjà dans la commande
    order_product, created_order_product = OrderProduct.objects.get_or_create(order=order, product=product)

    if created_order_product:
        order_product.quantity = 1  
    else:
        order_product.quantity += 1

    order_product.save() 

    # Calculer le montant total de la commande
    order.montant = sum(op.tatol_amount() for op in order.orderproduct_set.all())
    order.save()
    
    return redirect('store:home')

# -------------------------------------------------LE CONTENU DU PANIER-------------------------------------------------------------------#
def cart(request):
    order = get_object_or_404(Order, user = request.user, ordered = False)
    order_products = order.orderproduct_set.all()
    return render(request, "store/cart.html", {"orders": order, "order_products": order_products, "montant": order.montant})


# -----------------------------------------------VIDER LE PANIER--------------------------------------------------------------------------#
def cart_delete(request):
    cart = Cart.objects.get(user = request.user)
    cart.order_set.all().filter(user = request.user, ordered = False).delete()
    return redirect("store:home")

# ---------------------------------------------PAGE DE PAIEMENT---------------------------------------------------------------------------#
def form_pai(request):
    order = get_object_or_404(Order, user = request.user, ordered = False)
    return render(request, 'store/form_pai.html', {'montant': order.montant})


# -----------------------------------------------RECU DE PAIMENT--------------------------------------------------------------------------#
def recu(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order_products = order.orderproduct_set.all()
    html_string = render_to_string('store/recu.html', {"order_products": order_products, "Order": order, })
    # css_files = [
    #              CSS(settings.STATIC_URL + 'store/css/all.min.css'),
    #              CSS(settings.STATIC_URL + 'store/css/bootstrap.min.css'),
    #              CSS(settings.STATIC_URL + 'store/css/recu.css'),]
    pdf_file = HTML(string=html_string).write_pdf()
    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = f'attachement; filename="recu_{order.pk}.pdf"'
    return response
      



def paiement(request):
    # recuperation de l'addresse de livraison 
    if request.method == 'POST':
        pays = request.POST.get('pays')
        ville = request.POST.get('ville')
        zip = request.POST.get('zip')
        ShippingAddress.objects.create(user = request.user, pays = pays, ville = ville, zip_code = zip)

    # l'attribution de l'addrese à la commnde
    addrese = ShippingAddress.objects.filter(user=request.user).last()
    if addrese is not None:
        order = Order.objects.get(user=request.user, ordered=False)
        order.shippingaddress = addrese
        order.save() 

    # recuperation des donnees du payement 
    order = get_object_or_404(Order, user = request.user, ordered = False)
    cart = get_object_or_404(Cart, user = request.user)
    if request.method == 'POST':
        tel = request.POST.get('tel')
        Paiement.objects.create(user = request.user, cart = cart, mount = order.montant)
        return redirect('store:home')

    return render(request, 'store/form_pai.html')

# ----------------------------------------------COMMANDE A LIVREE-------------------------------------------------------------------------#
class OrderListView(ListView):
    queryset = Order.objects.filter(delivred = "En_attente")
    template_name = "store/commandealivre.html"
     
# -------------------------------------------METTRE A JOUR UNE COMMANDE-------------------------------------------------------------------#
class OrderUpdateView(UpdateView):
    model = Order
    template_name = "store/commandeupdate.html"
    form_class = formOrder
    success_url = reverse_lazy("store:alivre")

# ----------------------------------------SYSTEME DE PAIEMENT AVEC PAYPAL-----------------------------------------------------------------#
def checkout(request):
    order = get_object_or_404(Order, user = request.user, ordered = False)
    order.montant = order.quantity * sum(product.price for product in order.products.all())

    if request.method == "POST":
        # Créer un objet de paiement
        payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "paypal"
            },
            "redirect_urls": {
                "return_url": "http://localhost:8000/store/payment/execute/",
                "cancel_url": "http://localhost:8000/store/"
            },
            "transactions": [{
                "amount": {
                    "total": order.montant,
                    "currency": "USD"
                },
                "description": "la transaction vers le site Alfa"
            }]
        })

        # Créer le paiement
        if payment.create():
            print("Payment created successfully")
            for link in payment.links:
                if link.rel == "approval_url":
                    approval_url = str(link.href)
                    return redirect(approval_url)
        else:
            print(payment.error)

    return render(request, 'checkout.html')

def execute_payment(request):
    payment_id = request.GET.get('paymentId')
    payer_id = request.GET.get('PayerID')

    payment = paypalrestsdk.Payment.find(payment_id)

    if payment.execute({"payer_id": payer_id}):
        return HttpResponse("Payment executed successfully")
    else:
        return HttpResponse("Payment execution failed")



def essairecu(request):
    order = get_object_or_404(Order, pk=39)

shop/store/templates/store/cart.html
{% extends "base.html" %}

<!-- {% load multiplication_tag %} -->
{% block content %}
{% load static %}
    <div class="container-fluid mt-3" style="min-height: 45vh;">
        <div class="row">
            <div class="col-md-6">
                <h5 class="text text-center">Le contenu de votre panier  </h5>
                <table class="table table-striped table-bordered table-hover table-sm">
                    <caption>le panier de {{ user.username }} </caption>
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">Produit</th>
                            <th class="text-center">quantité</th>
                            <th class="text-center">Prix</th>
                            <th class="text-center">Modifier</th>
                        </tr>
                    </thead>

                    <tbody >
                        {% for order in order_products %}
                        <tr>
                            <td class="text-center">{{ order.product.name }}</td>
                            <td class="text-center">{{ order.quantity }}</td>
                            <td class="text-center">${{ order.product.price|multiply:order.quantity }}</td>
                            <td class="text-center">
                                <span><i class="text-danger fas fa-minus" style="margin: 0 5px; "></i></span>
                                <span><i class="text-success fas fa-plus" style="margin: 0 5px; "></i></span>
                            </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-info" style="font-weight: 600;">Total à payer </td>
                            <td colspan="2" style="text-align: end; font-weight: 600;"> ${{ montant }} </td>  
                        </tr>
                    </tfoot>
                </table> 
            </div>
            <div class="col-md-6">
                <h5 class="text text-center">Choisir le système de payement </h5>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 w-50">
                            <form action="{% url 'store:checkout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn"><video src="{% static 'store/img/paypal.mp4' %}" class="img-fluid" muted loop autoplay></video></button>
                            </form>
                            {% comment %} <a href="" class="">
                                <video src="{% static 'store/img/paypal.mp4' %}" class="img-fluid" muted loop autoplay></video>
                            </a> {% endcomment %}
                        </div>
                        <div class="col-md-6 w-50">
                            <a href="{% url 'store:form-pai' %}"class="">
                                <img src="{% static 'store/img/om.jpg' %}" alt="" srcset="" class="img-fluid">
                            </a>
                            <a href="{% url 'store:cart-delete' %}"  class="form-control col-sm-12 bg-warning mt-1 text-center text-danger" style="font-weight:600;"> Vider le Panier</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



{% comment %} person : b.2=E3P7
sb-f3opb33640559@personal.example.com

busness : FtW96-B*
sb-pfumt33673051@business.example.com {% endcomment %}

shop/store/templates/store/choix_sys_pai.html
{% extends 'base.html' %}

{% block content %}
 
{% endblock %}

shop/store/templates/store/commandealivre.html
{% extends "base.html" %}

{% block content %}
    <div style="min-height: 61vh;">
        <table class="table table-striped table-bordered table-hover table-sm" >
            <caption>liste de commande non livré  </caption>
            <thead class="thead-light">
            <tr>
                <th class="text-center">Client</th>
                <th class="text-center">Address</th>
                <th class="text-center">Date</th>
                <th class="text-center">Etat</th>
            </tr>
            </thead>
            {% for order in order_list %}
            <tr>
                <td class="text-center">{{ order.user }}</td>
                <td class="text-center">{{ order.shippingaddress }}</td>
                <td class="text-center">{{ order.ordered_date }}</td>
                <td class="text-center"><a href="{% url 'store:editorder' pk=order.pk %}"> {{ order.delivred }} </a></td>
            </tr>
            {% endfor %}
        </table> 
    </div>

{% endblock content %}

shop/store/templates/store/contact.html
{% extends "base.html" %}

{% block content %}

<section class="section contact m-4">

    <div class="row gy-4">

        <div class="col-xl-6">

            <div class="row">
                <div class="col-lg-6">
                    <div class="info-box card">
                        <i class="bi bi-geo-alt"></i>
                        <h3>Addresse</h3>
                        <p>H108 HAFIA,<br>GUINNEE, GU 535022</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="info-box card">
                        <i class="bi bi-telephone"></i>
                        <h3>Nous Appellez</h3>
                        <p>+224 621 68 24 96<br>+224 666 98 10 57</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="info-box card">
                        <i class="bi bi-envelope"></i>
                        <h3>Nos Email</h3>
                        <p>info@example.com<br>contact@example.com</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="info-box card">
                        <i class="bi bi-clock"></i>
                        <h3>Jour Ouvert</h3>
                        <p>Lundi - Samedi<br>08H:00 - 18H:00</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-6">
            <div class="card p-4">
                <form action="{% url 'store:contact' %}" method="post" class="">
                    {% csrf_token %}
                    <div class="row gy-4">

                        <div class="col-md-6 my-3">
                            <input type="text" name="nom" class="form-control" placeholder="Votre Nom" required>
                        </div>

                        <div class="col-md-6  my-3">
                            <input type="email" class="form-control" name="email" placeholder="Votre Email" required>
                        </div>

                        <div class="col-md-12 my-2">
                            <input type="text" class="form-control" name="sujet" placeholder="Sujet" required>
                        </div>

                        <div class="col-md-12 my-3">
                            <textarea class="form-control" name="message" rows="6" placeholder="Message" required></textarea>
                        </div>

                        <div class="col-md-12 text-center" style="margin-top: 11px;">
                            <button type="submit" class="btn btn-primary">Send Message</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>

    </div>

  </section>



{% endblock %}

shop/store/templates/store/detail.html
{% extends "base.html" %}


{% block content %}
    <div class="content-detail">         
        <div class="itmes-detail">
            <div >
                <img src="{{ product.thumbnail.url }}" alt="{{ product.name }}" class="img-fluid img-thumbnail ">
            </div>
            <div class="prix">
                {% if user.is_authenticated %}            
                    <span class="btn col-md-6 btn-success text-light">Prix : ${{ product.price }}</span>
                    <a href="{% url 'store:add-to-cart' product.pk %}" class=" btn btn-primary col-md-6">Ajouter au panier</a>  
                {% else %}
                    <span class="btn col-md-12 btn-success text-light">Prix : ${{ product.price }}</span>    
                {% endif %} 
            </div>
        </div>  
        <div>
            <p >{{ product.description }}</p>
        </div>
    </div>
{% endblock %}

shop/store/templates/store/form_pai.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mt-3" style="min-height: 58.2vh;">
    <form action="{% url 'store:paiement' %}" method="POST" class="form col-12">
        {% csrf_token %}

        <div class="row">
            <!-- formulaire de paiement -->
            <div class="col-md-6">
                <h5 class="text-center text-muted">Paiement</h5>
                    
                <div class="form-group col-12">
                    <input type="number" id="tel" name="tel" class="form-control" placeholder="téléphone ">
                </div>
                
                <div class="form-group col-12">
                    <input type="text" id="montant" name="montant" readonly  value="${{ montant }}" class="form-control">  
                </div>

                <div class="form-group col-12">
                    <button type="submit" class="form-control btn btn-success">effectuer</button>
                </div>
            </div>

            <!-- formulaire d'addresse  -->
            <div class="col-md-6">
                <div class="form-group col-12">
                    <h5 class="text text-center text-muted">Votre addresse de livraison</h5>
                    <select name="pays" id=""  class="form-control" >
                        <option value="" >------------votre pays------------</option>
                        <option value="Guinee">Guinée</option>
                        <option value="Senegal">Senegal</option>
                        <option value="Mali">Mali</option>
                        <option value="Ghana">Ghana</option>
                        <option value="Maroc">Maroc</option>
                    </select>
                </div>
                 
                <div class="form-group col-12">
                    <input type="text" id="ville" name="ville"  class="form-control" placeholder="ville">
                </div>

                <div class="form-group col-12">                      
                    <input type="text" id="zip" name="zip"  class="form-control" placeholder="addresse postale">
                </div>
            </div>


        </div>
    </form>
</div>


{% endblock %}

shop/store/templates/store/index.html
{% extends "base.html" %}

{% load static %}




{% block content %}

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'store/img/Christian Dior Homme(JPG).jpg' %}" class="d-block w-100" alt="slider1" style="height: 500px;">
        <div class="carousel-caption bgslid  d-none d-md-block div">
          <h5>Avec Alfa shop</h5>
          <p>Explorez nos dernières collections et profitez de réductions exclusives !</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'store/img/13088655159594005(JPG).jpg' %}" class="d-block w-100" alt="slider2" style="height: 500px;">
        <div class="carousel-caption bgslid  d-none d-md-block div">
          <h5>Second slide label</h5>
          <p>Decouvrez des produits de qualité à des prix imbattables !</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'store/img/2181499814444567(JPG).jpg' %}" class="d-block w-100" alt="slider3" style="height: 500px;">
        <div class="carousel-caption bgslid d-none d-md-block div">
          <h5>Third slide label</h5>
          <p>Livraison rapide et gratuite sur toutes vos commandes !</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
  </div>
   
  <div id="content">
    {% for item in product %}
    <div class="card" style="width: 15rem;">
      <a href="{% url 'store:detail' pk=item.pk %}" >
        <img src="{{ item.thumbnail.url }}" alt="{{ item.name }}" class="img-fluid card-img-top" style="height: 240px;">
      </a>
      <!-- <img src="..." class="card-img-top" alt="..."> -->
      <div class="card-body">
          <h5 class="card-title">{{ item.name }}</h5>
          <p class="card-text">{{ item.description|truncatewords:5 }}</p>
          <a href="{% url 'store:detail' pk=item.pk %}" class="btn btn-secondary">voir plus ...</a>
      </div>
    </div>
    {% endfor %}
  </div>


{% endblock %}

shop/store/templates/store/product_form.html
{% extends "base.html" %}

{% block content %}

   <div class="container-fluid img-thumbnail col-8 col-sm-7 col-md-4 " >
    <h5 class="text-center text-muted">Ajout de produit</h5>
       
        <form action="{% url 'store:create' %}" method="POST" class="form ", enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="form-control col-12 bg-info text-center d-inline-block">
                    Ajouter
                </button>

        </form>
   </div> 
{% endblock %}

shop/store/templates/store/search.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid">
        {% if product %}
            <div class="row">
                {% for item in product %}
                <div class="col-12 col-sm-9 col-md-4 col-lg-2">
                        <div>
                            <h3 class="text-info ">{{ item.name }}</h3>
                            <a href="{% url 'store:detail' pk=item.pk %}">
                                <img src="{{ item.thumbnail.url }}" alt="{{ item.name }}" class="img-fluid img-thumbnail ">
                            </a>
                        </div>
                </div>
                {% endfor %}
            </div>

        {% else %}
            {% if query %}
                <span>aucun n'element ne corespond à {{ query }}</span>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}